### ISSUE TITLE
Unable to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by nschlewitz** [openslice/io.openslice.main#1]
Hello,

I tried to install Openslice but had an issue during installation

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for io.openslice.main 1.0.2-SNAPSHOT:
[INFO] 
[INFO] io.openslice.sol005nbi.osm ......................... SUCCESS [04:22 min]
[INFO] io.openslice.sol005nbi.osm7 ........................ SUCCESS [ 17.793 s]
[INFO] io.openslice.sol005nbi.osm8 ........................ SUCCESS [  8.192 s]
[INFO] io.openslice.sol005nbi.osm7 ........................ SUCCESS [  9.195 s]
[INFO] io.openslice.main .................................. SUCCESS [  0.841 s]
[INFO] io.openslice.model ................................. SUCCESS [  8.448 s]
[INFO] io.openslice.centrallog.client ..................... SUCCESS [ 11.282 s]
[INFO] io.openslice.portal.api ............................ FAILURE [ 44.959 s]
[INFO] io.openslice.tmf.api ............................... SKIPPED
[INFO] io.openslice.manoclient ............................ SKIPPED
[INFO] io.openslice.bugzilla .............................. SKIPPED
[INFO] io.openslice.centrallog.service .................... SKIPPED
[INFO] io.openslice.osom .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:27 min
[INFO] Finished at: 2021-01-25T14:42:46Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project io.openslice.portal.api: Could not resolve dependencies for project io.openslice:io.openslice.portal.api:jar:1.0.2-SNAPSHOT: Could not find artifact io.openslice.sol005nbi:io.openslice.sol005nbi.osm5:jar:1.0.2-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :io.openslice.portal.api

Below is my environment:

ensu7375@yd-5CG4460B14:~/openslice_install$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
ensu7375@yd-5CG4460B14:~/openslice_install$ sudo docker info
[sudo] Mot de passe de ensu7375 : 
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.674GiB
 Name: yd-5CG4460B14
 ID: ZVWT:3DMO:OS2N:QO5R:YYHW:RCX3:SQBG:ZIDM:2FDV:PVMV:ODA4:EQK7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

Any idea ? I will search on ly own side as well.
Many thanks,

Nicolas

**Comment by ctranoris** [comment]
hi, could you please try on the development branch?

**Comment by nschlewitz** [comment]
Same issue: 

[INFO] Reactor Summary for io.openslice.main 1.0.2-SNAPSHOT:
[INFO] 
[INFO] io.openslice.sol005nbi.osm ......................... SUCCESS [  2.628 s]
[INFO] io.openslice.sol005nbi.osm7 ........................ SUCCESS [ 13.112 s]
[INFO] io.openslice.sol005nbi.osm8 ........................ SUCCESS [  7.410 s]
[INFO] io.openslice.sol005nbi.osm7 ........................ SUCCESS [  3.388 s]
[INFO] io.openslice.main .................................. SUCCESS [  0.060 s]
[INFO] io.openslice.model ................................. SUCCESS [  0.915 s]
[INFO] io.openslice.centrallog.client ..................... SUCCESS [  0.944 s]
[INFO] io.openslice.portal.api ............................ FAILURE [  0.855 s]
[INFO] io.openslice.tmf.api ............................... SKIPPED
[INFO] io.openslice.manoclient ............................ SKIPPED
[INFO] io.openslice.bugzilla .............................. SKIPPED
[INFO] io.openslice.centrallog.service .................... SKIPPED
[INFO] io.openslice.osom .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.020 s
[INFO] Finished at: 2021-01-25T15:13:25Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project io.openslice.portal.api: Could not resolve dependencies for project io.openslice:io.openslice.portal.api:jar:1.0.2-SNAPSHOT: Could not find artifact io.openslice.sol005nbi:io.openslice.sol005nbi.osm5:jar:1.0.2-SNAPSHOT -> [Help 1]


in deploy.sh I have changed git checkout master in git checkout develop

**Comment by ctranoris** [comment]
Can you try with this one:
https://raw.githubusercontent.com/openslice/io.openslice.main/develop/compose/deploy-develop.sh

**Comment by nschlewitz** [comment]
Thanks to you !

[INFO] io.openslice.sol005nbi.osm ......................... SUCCESS [  2.636 s]
[INFO] io.openslice.sol005nbi.osm7 ........................ SUCCESS [ 13.214 s]
[INFO] io.openslice.sol005nbi.osm8 ........................ SUCCESS [  7.331 s]
[INFO] io.openslice.sol005nbi.osm7 ........................ SUCCESS [  3.586 s]
[INFO] io.openslice.main .................................. SUCCESS [  0.074 s]
[INFO] io.openslice.model ................................. SUCCESS [  0.893 s]
[INFO] io.openslice.centrallog.client ..................... SUCCESS [  0.761 s]
[INFO] io.openslice.portal.api ............................ SUCCESS [ 18.524 s]
[INFO] io.openslice.tmf.api ............................... SUCCESS [ 17.404 s]
[INFO] io.openslice.manoclient ............................ SUCCESS [  8.144 s]
[INFO] io.openslice.bugzilla .............................. SUCCESS [  1.049 s]
[INFO] io.openslice.centrallog.service .................... SUCCESS [  0.677 s]
[INFO] io.openslice.osom .................................. SUCCESS [ 23.833 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

By the way, I have change /home/ubuntu by my home dir in deploy.sh and reported this in deploy-develop.sh

I will move forward and have a look at the rest of the installation procedure.
Once I'll get this up and running, I'll try to deploy this in my lab wich is by the way behind a corporate proxy to reach the Internet so I expect more pleasure :-)

Until then, Thank you very much for your quick answer and have a nice evening

**Comment by ctranoris** [comment]
ah ok thanks for the note

**Comment by nschlewitz** [comment]
Installation Successful. Thanks again for your help. I have another issue to sign in my local instance of openslice. I will search on my side and maybe ask you in another issue if I don't succeed.
