### ISSUE TITLE
Simple Ubuntu deployment

### ISSUE THREAD

**Issue by Thorfinn3** [openslice/io.openslice.main#2]
Hello,

I tried to instantiate a simple Ubuntu VNF using Openslice but I am in trouble (All works well when I just use OSM).
I worked on develop branch (I actually work with @nschlewitz). 

First I onboarded my VNF and NS with my Openslice on my OSM platform. I use NS and VNF package given in example by OSM (https://osm.etsi.org/gitlab/vnf-onboarding/osm-packages/-/tree/OSM-IM/ubuntu_cloudinit_ns ,
https://osm.etsi.org/gitlab/vnf-onboarding/osm-packages/-/tree/OSM-IM/ubuntu_cloudinit_vnf)

I have also specified my VIM in "Manage infrastructure" dashboard of nfvportal with my OSM vim informations :
`1   ln2ni-openstack-site    ln2ni-openstack-site                            3394ebce-e4e3-4665-b4f8-00a1da404186`

After that I imported my NSD on the service portal, my parameters are default :
```
NSDID	2 (id)
ObMANOprovider_Name	OSM
OnBoardingStatus	ONBOARDED
PackageLocation	http://myopenslice2.org/osapi/packages/9b9c7f88-f137-4d36-9b3a-8e9ba848a2d5/ubuntu_cloudinit_ns.tar.gz (PackageLocation)
PackagingFormat	OSMvEIGHT (PackagingFormat)
Vendor	OSM (Vendor)
```
But  when choose to run my service order I have an error : 
```
{
    "code": "UNPROCESSABLE_ENTITY",
    "status": 422,
    "detail": "Format error at 'vnf' '[] is too short'  while 'validating input parameters'"
}
```
My logs : 
```{
   "id":16,
   "uuid":"4d7004cd-4407-4b65-9756-a027976d2639",
   "name":"Service Order 91d6e8d7-7acd-412d-a302-98f6216213b1",
   "mentor":{
      "id":1,
      "organization":"",
      "firstname":"Portal Administrator",
      "lastname":null,
      "email":"",
      "username":"admin",
      "active":true,
      "currentSessionID":null,
      "apikey":"f746e235-be81-4ad1-98de-741664af0feb",
      "createdAt":null,
      "roles":null
   },
   "infrastructureForAll":{
      "id":1,
      "organization":null,
      "name":"ln2ni-openstack-site",
      "email":null,
      "datacentername":"ln2ni-openstack-site",
      "vimid":"3394ebce-e4e3-4665-b4f8-00a1da404186"
   },
   "description":"Created automatically by OSOM for Service Order 91d6e8d7-7acd-412d-a302-98f6216213b1",
   "feedback":"{\n    \"code\": \"UNPROCESSABLE_ENTITY\",\n    \"status\": 422,\n    \"detail\": \"Format error at 'vnf' '[] is too short'  while 'validating input parameters'\"\n}\n",
   "instantiationconfig":null,
   "status":"FAILED",
   "dateCreated":1614266470000,
   "startReqDate":1614261791000,
   "endReqDate":1614348191000,
   "startDate":1614261791000,
   "endDate":1614348191000,
   "instanceId":null,
   "nsLcmOpOccId":null,
   "experiment":{
      "id":2,
      "uuid":"9b9c7f88-f137-4d36-9b3a-8e9ba848a2d5",
      "name":"ubuntu_cloudinit-ns",
      "constituentVxF":null,
      "experimentfOnBoardDescriptors":[
         
      ]
   },
   "owner":{
      "id":1,
      "organization":"",
      "firstname":"Portal Administrator",
      "lastname":null,
      "email":"",
      "username":"admin",
      "createdAt":null
   },
   "vxfPlacements":[
      
   ],
   "operationalStatus":null,
   "configStatus":null,
   "detailedStatus":null,
   "constituentVnfrIps":null,
   "nsr":null,
   "ns_nslcm_details":null,
   "experimentFullDetails":{
      "id":2,
      "owner":{
         "id":2,
         "organization":null,
         "firstname":null,
         "lastname":null,
         "email":"charles.picard3@gmail.com",
         "username":"opensliceadmin",
         "createdAt":null
      },
      "uuid":"9b9c7f88-f137-4d36-9b3a-8e9ba848a2d5",
      "name":"ubuntu_cloudinit-ns",
      "iconsrc":null,
      "shortDescription":"ubuntu_cloudinit-ns",
      "longDescription":"Generated by OSM package generator",
      "version":"1.0",
      "packageLocation":"http://myopenslice2.org/osapi/packages/9b9c7f88-f137-4d36-9b3a-8e9ba848a2d5/ubuntu_cloudinit_ns.tar.gz",
      "dateCreated":1614256523000,
      "dateUpdated":1614258643000,
      "categories":null,
      "extensions":null,
      "validationJobs":null,
      "screenshots":"",
      "vendor":"OSM",
      "published":false,
      "termsOfUse":null,
      "descriptor":"nsd:nsd-catalog:\n    nsd:\n    -   id: ubuntu_cloudinit-ns\n        name: ubuntu_cloudinit-ns\n        short-name: ubuntu_cloudinit-ns\n        description: Generated by OSM package generator\n        vendor: OSM\n        version: '1.0'\n        constituent-vnfd:\n        -   member-vnf-index: 1\n            vnfd-id-ref: ubuntu_cloudinit-vnf\n        vld:\n        # Networks for the VNFs\n        -   id: mgmtnet\n            name: mgmtnet\n            short-name: mgmtnet\n            type: ELAN\n            mgmt-network: true\n            # vim-network-name: <update>\n            vnfd-connection-point-ref:\n            -   member-vnf-index-ref: 1\n                vnfd-id-ref: ubuntu_cloudinit-vnf\n                vnfd-connection-point-ref: vnf-cp0\n",
      "descriptorHTML":"<h3>ubuntu_cloudinit-ns</h3><br><b>Vendor: </b>OSM<br><b>Version: </b>1.0<br><b>Description: </b>Generated by OSM package generator<br><b>VNF Count: </b>1<br><b>VM Count: </b>0<br><b>vCPU Count: </b>0<br><b>Memory: </b>0 MB<br><b>Storage: </b>0 GB<br><h2>ConstituentVnfds</h2><br><b>VnfdId: </b>ubuntu_cloudinit-vnf<br>",
      "valid":false,
      "validationStatus":"NOT_STARTED",
      "packagingFormat":"OSMvEIGHT",
      "experimentOnBoardDescriptors":[
         {
            "id":2,
            "obMANOprovider":{
               "id":12,
               "name":"OSM",
               "description":null,
               "supportedMANOplatform":{
                  "id":9,
                  "name":"OSMvEIGHT",
                  "version":"OSMvEIGHT",
                  "description":null
               },
               "apiEndpoint":"@NBI IP",
               "authorizationBasicHeader":null,
               "username":"admin",
               "password":"admin",
               "project":"admin",
               "enabledForONBOARDING":true
            },
            "onBoardingStatus":"ONBOARDED",
            "lastOnboarding":1614256524000,
            "deployId":"03cc5cea-7c03-4c8a-baa2-676d99956a81",
            "feedbackMessage":"NSD Onboarded Successfully",
            "uuid":"9058e879-9cab-4aef-92dd-aafcfa4b5264",
            "experimentMANOProviderID":"ubuntu_cloudinit-ns",
            "experimentid":2
         }
      ],
      "constituentVxF":null,
      "experimentfOnBoardDescriptors":[
         {
            "id":2,
            "obMANOprovider":{
               "id":12,
               "name":"OSM",
               "description":null,
               "supportedMANOplatform":{
                  "id":9,
                  "name":"OSMvEIGHT",
                  "version":"OSMvEIGHT",
                  "description":null
               },
               "apiEndpoint":"@NBI IP",
               "authorizationBasicHeader":null,
               "username":"admin",
               "password":"admin",
               "project":"admin",
               "enabledForONBOARDING":true
            },
            "onBoardingStatus":"ONBOARDED",
            "lastOnboarding":1614256524000,
            "deployId":"03cc5cea-7c03-4c8a-baa2-676d99956a81",
            "feedbackMessage":"NSD Onboarded Successfully",
            "uuid":"9058e879-9cab-4aef-92dd-aafcfa4b5264",
            "experimentMANOProviderID":"ubuntu_cloudinit-ns",
            "experimentid":2
         }
      ]
   },
   "scheduledStartDate":"2021-02-25T00:00:00Z",
   "scheduledEndDate":"2021-02-26T23:59:59Z"
}```
```
I already tested another configuration :
```
ubuntu_cloudinit-ns::NSDID	2 (id)
ubuntu_cloudinit-ns::ObMANOprovider_Name	OSM
ubuntu_cloudinit-ns::OnBoardingStatus	ONBOARDED
ubuntu_cloudinit-ns::PackageLocation	http://myopenslice2.org/osapi/packages/9b9c7f88-f137-4d36-9b3a-8e9ba848a2d5/ubuntu_cloudinit_ns.tar.gz (PackageLocation)
ubuntu_cloudinit-ns::PackagingFormat	OSMvEIGHT (PackagingFormat)
ubuntu_cloudinit-ns::Vendor	OSM (Vendor)
```
And it works, my order is active and completed, i don't no why. 
```
Service reserved
written by API @ 26 Feb 2021, 9:18 am
Service Created by AutomationCheck
written by OSOM @ 26 Feb 2021, 9:18 am
Service feasibilityChecked
written by API @ 26 Feb 2021, 9:18 am
Service active
written by API @ 26 Feb 2021, 9:18 am
Local Service Orchestration initialized for spec:Copy of ubuntu_cloudinit-ns done!
written by OSOM @ 26 Feb 2021, 9:18 am
Update Service Order State to: active.
written by OSOM @ 26 Feb 2021, 9:18 am
```
Nevertheless my service is not instantiate anywhere in this case.

I am sorry but I don't understand well which characteristics has to be given and where I can found logs to debug efficiently. 
I just want to test Openslice on a basic use case to better understand how it works (just Ubuntu or Cirros VM deployment on a VIM with Openslice and OSM).
I hope my explanations was clear, don't hesitate to tell me if I haven't put my question on the right place or if some points need to be detailed.

Thanks a lot,
Charles

**Comment by ctranoris** [comment]
Hello,
for monitoring. portainer is also there in port :9000 so you can view the logs of any container.
in this case you can focus on OSOM and manoclient.
The problem seems on OSM side through the call from openslice manoclient to OSM.
Is your VNF working in OSM? Does it need some initial configuration to run?
You can also check first your VNFs/NSDs in the nfvportal UIs (insted of creating RFS/CFS which is more time consuming)
You can go to nfvportal 
to Deployments>Deploy Network services
Requested Deployed NSDs and request New deployment.

Fill the form and save the request

Then from the menu Admin->registered deployment experiments 
You go to the form Admin all Deployed NSDs.
There edit the requested deployment, and change the status from UNDER_REVIEW to SCHEDULED
Then the NSD will be scheduled for provisioning by openslice.
This is a fast shortcut to help debugging

I hope it's clear. Let us know

**Comment by Thorfinn3** [comment]
Hello,

Thank you very much for your prompt response.
Indeed I have a problem of parameter, would you have by chance an example of description on which I can rely in term of format? 

Normally after switching to SCHEDULED and I have no error, this should mean that my parameters are good and that I can transfer them to the service?

Excuse me for all these questions, I would like to understand well so that I don't have to bother you anymore.

**Comment by ctranoris** [comment]
Yes this is a good way if it works first on SCHEDULED. Have in mind that there is a configuration field there to apply any initial configuration to OSM.


Also, now for the service design (RFS/CFS):

### Initial configuration

if you have an initial configuration that needs to be applied in the NSD deployment, then you go to the RFS (or CFS) and in Service Specification Characteristics go and edit the CONFIG characteristic. 
You can add in the Service Characteristic Value, in the Value field something like the following example which gives a floating IP to a VNF:

```
{ "nsdId": "e855be91-567b-45cf-9f86-18653e7ea", "vimAccountId": "4efd8bf4-5292-4634-87b7-7b3d49108" , "vnf": [ {"member-vnf-index": "1", "vdu": [ {"id": "MyCharmedVNF-VM", "interface": [{"name": "eth0", "floating-ip-required": true }]}]}]}
 
```

You can leave the Alias and Unit of Measure as is. Check also the is Default.

have a look also here (again documentation in development branch..):

https://openslice.readthedocs.io/en/develop/catalogs/

I understand this is not the best way to do things and documentation is a little bit poor but we try to improve in future.

There is also a slack channel were we try to be responsive: https://openslice.slack.com/

**Comment by Thorfinn3** [comment]
Thank you very much for all your information, I will get back to you as soon as I have a result.

No worries about the documentation, I totally understand.

**Comment by Thorfinn3** [comment]
It works !

Thank you a lot ! I better understand how to works with parameters. 
Have a nice week-end

**Comment by modyngs** [comment]
> I understand this is not the best way to do things and documentation is a little bit poor but we try to improve in future.
> 
> There is also a slack channel were we try to be responsive: https://openslice.slack.com/

Hi @ctranoris 
May i join the Slack group for OpenSlice?

I tried to join but there was just available with @orange domain!

Thanks
Best regards

**Comment by ctranoris** [comment]
hello,

yes of course you can join. 
Can you try again?

**Comment by modyngs** [comment]
Sorry but when i click on signing in with google
i get the following message

![image](https://user-images.githubusercontent.com/82098055/176177344-9e45c969-c094-49d0-80f2-4f9a6c4875df.png)


Is this the right email?
It looks like there isn’t an account on openslice tied to this email address.

**Comment by modyngs** [comment]
@ctranoris 
How can i create account on the openslice.slack?

Thanks
best regards

**Comment by ctranoris** [comment]
perhaps you can use the Sign in with Google

**Comment by modyngs** [comment]
@ctranoris 
I've tried it and then the RED alert shown!

There is an option inside Slack that invite People from inside!

![image](https://user-images.githubusercontent.com/82098055/176179838-bc838093-9e6d-4d84-af64-7eee9dc3b7a9.png)

**Comment by ctranoris** [comment]
ok. in any case I send you an invitation

**Comment by modyngs** [comment]
Thanks
