### ISSUE TITLE
Trying to build the OpenSlice environment

### ISSUE THREAD

**Issue by javiergorostiaga** [openslice/io.openslice.main#29]
I'm experiencing issues when trying to run Docker Compose on my machine. The version specified in my `docker-compose.yaml` file seems to be obsolete, and I'm also having trouble pulling the `jboss/keycloak` image from Docker Hub.

## Steps to Reproduce:
1. Navigate to the `io.openslice.main/compose` directory.
2. Run the command `sudo docker compose --profile prod up -d  --build`.

## Additional Information:
- **Operating System**: Ubuntu 22.04.01
- **Architecture**: x86_64
- **Docker Version**: 26.1.0
- **Docker Compose Version**: 1.29.2

## Logs/Screenshots:
Apparently is built successfully.
![Screenshot from 2024-05-24 09-51-20](https://github.com/openslice/io.openslice.main/assets/56133484/d1bf766c-89e4-4074-aa59-6bb402c30e04)
I have just modified this file to be able to see those on my local machine:
![Screenshot from 2024-05-24 09-58-47](https://github.com/openslice/io.openslice.main/assets/56133484/ad3ead33-5f4e-4698-98e2-9522686923d4)
This is what I get when I try to run it:
![Screenshot from 2024-05-24 10-16-22](https://github.com/openslice/io.openslice.main/assets/56133484/bea3c39e-aa38-4465-b48d-29f088bba008)

## Possible Solution:
I'm not sure how to resolve this issue. Any help would be appreciated.

**Comment by ctranoris** [comment]
HI, the project has migrated to ETSI. The github repository is no longer used
Please see here for more information 
https://osl.etsi.org/
https://osl.etsi.org/documentation/latest/

The code is here: 
https://labs.etsi.org/rep/osl/

cc @kostistr
