### ISSUE TITLE
First deployment always fails

### ISSUE THREAD

**Issue by kostistr** [openslice/io.openslice.main#5]
After changes to the logic of CSS imports (https://github.com/openslice/io.openslice.tmf.web/issues/48), while building the application the file /src/assets/config/theming.scss must always be present, or else build fails.
Update the deploy.sh files to incorporate the above logic.
if (file_not_present) > /src/assets/config/theming.default.scss -> /src/assets/config/theming.scss

**Comment by b3c3ll** [comment]
@kostistr 
Hi
After posting the issue #8, I saw yours!

Can you please guide me through this?

the installation process is as follows:

cd && mkdir openslice && cd openslice
wget https://raw.githubusercontent.com/openslice/io.openslice.main/develop/compose/deploy-develop.sh
chmod +x deploy-develop.sh
sudo ./deploy-develop.sh


So i'm using develop brach!
Would it be possible to use master branch for the fix?
or any other idea that can help to deploy successfully?

Thanks
Regards

**Comment by b3c3ll** [comment]
> if (file_not_present) > /src/assets/config/theming.default.scss -> /src/assets/config/theming.scss

I'm not much familiar with openslice
but as my undrestanding this would be the solution

```
if [ ! -f  "PATH_TO OPENSLICE/src/assets/config/theming.scss" ]; then
    cp /src/assets/config/theming.default.scss /src/assets/config/theming.scss
fi
```

This says if the  file was not available then copy it

**Comment by kostistr** [comment]
Hello @b3c3ll,

Thank you very much for your feedback. This exactly is the solution, which is included in our regular code housekeeping, but not yet updated. Please keep following the develop branch, that has all the latest functionalities. With our latest push, we will update the main branch as well to correctly reflect it's state.

**Comment by b3c3ll** [comment]
@kostistr 
Sure, 
Around the time i commented [5 Hours ago], i also pushed a PR into this repo!
would you please merge this?
Thanks
Best regards
