### ISSUE TITLE
add credentials to access dockerhub

### ISSUE THREAD

**Issue by dimitrisgiannopoulos** [openslice/io.openslice.main#7]
We need to add credentials to Github, so the docker images are built andpushed to dockerhub automatically.
To do this, one of the contributors must go to each repository's **Settings** -> **secrets and variables** -> **Actions**, and add two variables: 

- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN

**Comment by ctranoris** [comment]
communicated offline

**Comment by dimitrisgiannopoulos** [comment]
Credentials added for all relevant repositories.
